name: Terraform

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_keybase_txt_record: ${{ secrets.TF_VAR_KEYBASE_TXT_RECORD }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform validate -no-color

      # horrible hack because i dont have the time to get creds
      # remove in next commit and force push to overwrite it lol
      - run: terraform import aws_route53_record.txt Z01764393G8GHB9SR3BK3_amber.vision_TXT

      - run: terraform apply -auto-approve -input=false
