name: Terraform

on: push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_keybase_txt_record: ${{ secrets.TF_VAR_KEYBASE_TXT_RECORD }}
  TF_CLI_ARGS: "-no-color"

jobs:
  fmt_validate_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan
  
  apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform apply -auto-approve -input=false
